FROM postgres:16
ENV POSTGRES_DB=facebook
ENV POSTGRES_USER=sysfacebook
ENV POSTGRES_PASSWORD=123456
# Reemplaza 'copia_texto.sql' por el nombre REAL de tu archivo de texto
COPY facebook_final.sql /docker-entrypoint-initdb.d/init.sql